name: Snyk NodeJS Scan (SAST - code)

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snyk/actions/setup@master
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Run Snyk code to check for code vulnerabilities
      run: snyk code test --sarif | tee snyk_code.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Upload snyk code result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk_code.sarif
        category: snyk_SAST